version: "3.9"

services:
  user_service:
    build:
      context: ./user_service
    container_name: user_service
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]